sudo: required
# language: generic
services:
  - docker

before_install:
  - docker build -t boblaroc/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true boblaroc/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-528279850086"
  bcket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
