sudo: required
# language: generic
services:
  - docker

before_install:
  - docker build -t boblaroc/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true boblaroc/docker-react npm run test -- --coverage
